service: aws-node-express-dynamodb-api
frameworkVersion: '3'

custom:
  tableName: 'feature-flag-table-${sls:stage}'
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ FeatureFlagTable, Arn ]
  environment:
    FEATURE_FLAG_TABLE: ${self:custom.tableName}
    IS_OFFLINE: true

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    FeatureFlagTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: featureKey
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: featureKey
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
